[workspace]
name = "website_projects"
channels = ["conda-forge", "pytorch"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = ">=3.13,<3.14"
arviz = ">=0.22.0"
bambi = ">=0.16.0"
cvxpy = "*"
econml = "*"
orbit-ml = ">=1.1.4.9"
preliz = "*"
pymc = ">=5.27.0"
pymc-bart = ">=0.5.14"
pymc-extras = "*"
pymc-marketing = ">=0.17.0"
pyproj = "*"

[pypi-dependencies]
bayeux-ml = "*"
beartype = "*"
blackjax = ">=1.2.5"
category-encoders = "*"
darts = "*"
datasetsforecast = "*"
dowhy = "*"
dynamax = "*"
equinox = "*"
fastexcel = "*"
flax = "*"
funsor = "*"
geopandas = "*"
graphviz = "*"
ipykernel = "*"
ipython = "*"
ipywidgets = "*"
jax = ">=0.7.2"
jaxopt = "*"
jaxtyping = "*"
jupytext = "*"
lightgbm = "*"
marginaleffects = "*"
marimo = "*"
matplotlib = ">=3.10.0"
mlforecast = "*"
networkx = "*"
nbconvert = "*"
numpyro = ">=0.20.0"
nutpie = "*"
openpyxl = "*"
pandas = ">=2.2.3"
pandera = { version = "*", extras = ["polars"] }
polars = "<3.0"
pre-commit = "*"
pydantic = ">=2.11.7"
pyfixest = "<0.40.0"
pyro-ppl = ">=1.9.1"
rich = "*"
ruff = "*"
scikit-learn = ">=1.5.2"
seaborn = ">=0.13.2"
shap = "*"
statsforecast = "*"
statsmodels = ">=0.14.4"
tfp-nightly = "*"
tfp-causalimpact = "*"
utilsforecast = "*"
watermark = "*"
xgboost = "*"
